"""Corrigiendo relaciones

Revision ID: 8ca3d6208d95
Revises: 
Create Date: 2025-03-10 23:25:21.966162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca3d6208d95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debilidad1', sa.String(), nullable=False),
    sa.Column('debilidad2', sa.String(), nullable=False),
    sa.Column('debilidad3', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokedex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameEvo', sa.String(length=100), nullable=False),
    sa.Column('evolucion1', sa.String(), nullable=False),
    sa.Column('evolucion2', sa.String(), nullable=False),
    sa.Column('evolucion3', sa.String(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokedex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ataque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defensa', sa.String(), nullable=False),
    sa.Column('velocidad', sa.Integer(), nullable=False),
    sa.Column('ataque_especial', sa.String(), nullable=False),
    sa.Column('poke_id', sa.Integer(), nullable=False),
    sa.Column('evo_id', sa.Integer(), nullable=False),
    sa.Column('debilidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['debilidad_id'], ['debilidad.id'], ),
    sa.ForeignKeyConstraint(['evo_id'], ['evolucion.id'], ),
    sa.ForeignKeyConstraint(['poke_id'], ['pokedex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caracteristica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('habilidad', sa.String(), nullable=False),
    sa.Column('devilidad', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.Integer(), nullable=False),
    sa.Column('evo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['devilidad'], ['debilidad.id'], ),
    sa.ForeignKeyConstraint(['evo_id'], ['evolucion.id'], ),
    sa.ForeignKeyConstraint(['pokemon'], ['pokedex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caracteristica')
    op.drop_table('ataque')
    op.drop_table('evolucion')
    op.drop_table('pokedex')
    op.drop_table('debilidad')
    # ### end Alembic commands ###
